/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/extension/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extension module status
         * @description Reports whether the extension module is wired. Placeholder for phase 0.
         */
        get: operations["getExtensionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node health
         * @description Reports liveness, the running build and whether a cloud account is paired.
         */
        get: operations["getNodeHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library module status
         * @description Reports whether the library module is wired. Placeholder for phase 0.
         */
        get: operations["getLibraryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playback/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Playback module status
         * @description Reports whether the playback module is wired. Placeholder for phase 0.
         */
        get: operations["getPlaybackStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reader/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reader module status
         * @description Reports whether the reader module is wired. Placeholder for phase 0.
         */
        get: operations["getReaderStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync module status
         * @description Reports whether the sync module is wired. Placeholder for phase 0.
         */
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/torrent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Torrent module status
         * @description Reports whether the torrent module is wired. Placeholder for phase 0.
         */
        get: operations["getTorrentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Build timestamp.
             * @example 2026-08-27T12:00:00Z
             */
            built: string;
            /**
             * @description Git commit the build came from.
             * @example abc1234
             */
            commit: string;
            /** @description True when the node is paired with a cloud account. */
            linked: boolean;
            /**
             * @description Node status.
             * @example ok
             */
            status: string;
            /**
             * @description Semantic version of the running build.
             * @example 0.1.0
             */
            version: string;
        };
        StatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example library
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        StatusOutputBody1: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody1.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example torrent
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        StatusOutputBody2: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody2.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example playback
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        StatusOutputBody3: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody3.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example reader
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        StatusOutputBody4: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody4.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example sync
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        StatusOutputBody5: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody5.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example extension
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaErrorDetail = components['schemas']['ErrorDetail'];
export type SchemaErrorModel = components['schemas']['ErrorModel'];
export type SchemaHealthOutputBody = components['schemas']['HealthOutputBody'];
export type SchemaStatusOutputBody = components['schemas']['StatusOutputBody'];
export type SchemaStatusOutputBody1 = components['schemas']['StatusOutputBody1'];
export type SchemaStatusOutputBody2 = components['schemas']['StatusOutputBody2'];
export type SchemaStatusOutputBody3 = components['schemas']['StatusOutputBody3'];
export type SchemaStatusOutputBody4 = components['schemas']['StatusOutputBody4'];
export type SchemaStatusOutputBody5 = components['schemas']['StatusOutputBody5'];
export type $defs = Record<string, never>;
export interface operations {
    getExtensionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody5"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getNodeHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getLibraryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getPlaybackStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody2"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getReaderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody3"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody4"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getTorrentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody1"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
