root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/nodesrv.exe ./cmd/nodesrv"
bin = "tmp/nodesrv.exe"
delay = 500
include_ext = ["go", "sql", "yaml", "yml"]
exclude_dir = ["bin", "tmp", "docs", "api", "internal/platform/db/sqlc"]
exclude_regex = ["_test\\.go"]
stop_on_error = true
send_interrupt = true
kill_delay = "2s"

[log]
time = true

[misc]
clean_on_exit = true
