/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current account
         * @description Returns the signed-in account. Read from the database rather than from the session, so a change of role or name is visible immediately.
         */
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Registers an account and signs it in. The returned token is the session identifier; it is shown once and cannot be recovered.
         */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Exchanges credentials for a session identifier. Repeated failures throttle the account, not the address they come from.
         */
        post: operations["createSession"];
        /**
         * Sign out everywhere
         * @description Ends every session the account holds, including this one. Intended for a lost or stolen device.
         */
        delete: operations["deleteAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign out
         * @description Ends the session used to make this call. Revocation is immediate: the identifier is deleted, not denylisted.
         */
        delete: operations["deleteCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog module status
         * @description Reports whether the catalog module is wired. Placeholder for phase 0.
         */
        get: operations["pingCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Reports liveness and the build the process is running.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metadata/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metadata module status
         * @description Reports whether the metadata module is wired. Placeholder for phase 0.
         */
        get: operations["pingMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/moderation/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Moderation module status
         * @description Reports whether the moderation module is wired. Placeholder for phase 0.
         */
        get: operations["pingModeration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social module status
         * @description Reports whether the social module is wired. Placeholder for phase 0.
         */
        get: operations["pingSocial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClientRequirements: {
            /**
             * @description Oldest client build allowed to use cloud features. Empty means no minimum is enforced.
             * @example 1.2.0
             */
            min_supported?: string;
            /**
             * @description Newest available build, for a non-blocking update hint. Empty means no hint.
             * @example 1.4.0
             */
            recommended?: string;
            /**
             * @description Where to send the user to update. Always present when min_supported is set.
             * @example https://mediary.example/download
             */
            update_url?: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Build timestamp.
             * @example 2026-08-27T12:00:00Z
             */
            built: string;
            /** @description Which client builds this deployment serves. */
            client: components["schemas"]["ClientRequirements"];
            /**
             * @description Git commit the build came from.
             * @example abc1234
             */
            commit: string;
            /**
             * @description Service status.
             * @example ok
             */
            status: string;
            /**
             * @description Semantic version of the running build.
             * @example 0.1.0
             */
            version: string;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description The account's address.
             */
            email: string;
            /** @description The account's password. */
            password: string;
        };
        PingOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PingOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example catalog
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        PingOutputBody1: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PingOutputBody1.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example metadata
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        PingOutputBody2: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PingOutputBody2.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example social
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        PingOutputBody3: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PingOutputBody3.json
             */
            readonly $schema?: string;
            /**
             * @description Module name.
             * @example moderation
             */
            module: string;
            /** @description True when the module's dependencies are wired. */
            ready: boolean;
        };
        RegisterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RegisterInputBody.json
             */
            readonly $schema?: string;
            /** @description Name shown to other users. Must be unique, ignoring case. */
            display_name: string;
            /**
             * Format: email
             * @description Address to register. Stored lowercased.
             */
            email: string;
            /** @description At least 10 characters. No composition rules — length is what makes a password hard to guess. */
            password: string;
        };
        RevokedOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RevokedOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of sessions ended, including the current one.
             */
            revoked: number;
        };
        SessionBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SessionBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Absolute deadline. Activity extends the idle window, never this.
             */
            expires_at: string;
            /** @description Opaque session identifier. Send it as 'Authorization: Bearer <token>'. */
            token: string;
            /** @description The signed-in account. */
            user: components["schemas"]["UserBody"];
        };
        UserBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description When the account was created.
             */
            created_at: string;
            /** @description Name shown to other users. */
            display_name: string;
            /**
             * Format: email
             * @description The account's normalised address.
             */
            email: string;
            /** @description Whether the address has been confirmed. */
            email_verified: boolean;
            /**
             * Format: uuid
             * @description Stable account identifier.
             */
            id: string;
            /**
             * @description Permission level.
             * @enum {string}
             */
            role: "user" | "moderator" | "admin";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaClientRequirements = components['schemas']['ClientRequirements'];
export type SchemaErrorDetail = components['schemas']['ErrorDetail'];
export type SchemaErrorModel = components['schemas']['ErrorModel'];
export type SchemaHealthOutputBody = components['schemas']['HealthOutputBody'];
export type SchemaLoginInputBody = components['schemas']['LoginInputBody'];
export type SchemaPingOutputBody = components['schemas']['PingOutputBody'];
export type SchemaPingOutputBody1 = components['schemas']['PingOutputBody1'];
export type SchemaPingOutputBody2 = components['schemas']['PingOutputBody2'];
export type SchemaPingOutputBody3 = components['schemas']['PingOutputBody3'];
export type SchemaRegisterInputBody = components['schemas']['RegisterInputBody'];
export type SchemaRevokedOutputBody = components['schemas']['RevokedOutputBody'];
export type SchemaSessionBody = components['schemas']['SessionBody'];
export type SchemaUserBody = components['schemas']['UserBody'];
export type $defs = Record<string, never>;
export interface operations {
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    registerAccount: {
        parameters: {
            query?: never;
            header?: {
                /** @description Recorded with the session so a user can recognise it later. */
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Recorded with the session so a user can recognise it later. */
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokedOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    pingCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    pingMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingOutputBody1"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    pingModeration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingOutputBody3"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    pingSocial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingOutputBody2"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
