import type { components, operations } from './schema.gen'

/**
 * Named shortcuts into the generated cloud contract.
 *
 * `cloud.gen.ts` is generated by `npm run api:types:cloud` from the spec in the
 * sibling `mediary-contracts` checkout. That is a stand-in: once
 * `@mediaryorg/mediary-contracts` is published, the generation step goes away
 * and this file re-exports the package instead. See
 * mediary-contracts/docs/contracts-and-codegen.md.
 */

export type CloudSchemas = NonNullable<components['schemas']>

export type CloudOperation<Id extends keyof operations> = operations[Id]

export type CloudResponse<Id extends keyof operations> = operations[Id]['responses'] extends {
	200: { content: { 'application/json': infer Body } }
}
	? Body
	: never
