import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import reactPlugin from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'
import { readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import tseslint from 'typescript-eslint'

/*
 * ---------------------------------------------------------------------------
 * Architecture boundaries — see docs/architecture.md
 *
 *   app      composition
 *   modules  domain ownership     → core, ui, lib, sibling module public API
 *   core     app infrastructure   → lib
 *   ui       visual primitives    → lib
 *   lib      technical primitives → nothing
 *
 * This is a categorisation of ownership, not a layer hierarchy — but the
 * dependency *direction* between those categories is still one-way, and that
 * part is machine-checkable.
 *
 * ESLint sees one file at a time, so it enforces direction only. It cannot see
 * cycles: a cycle is a property of the graph, not of any single file. That is
 * what scripts/check-architecture.mjs is for. `npm run arch:check` runs both,
 * and violations are errors, not warnings.
 * ---------------------------------------------------------------------------
 */

/** Every alias pattern for a category: the bare alias plus everything under it. */
const alias = name => [`@${name}`, `@${name}/*`, `@${name}/*/**`]

/** One `no-restricted-imports` rule. `deny` holds category names. */
function layer(files, deny, message) {
	return {
		files,
		rules: {
			'no-restricted-imports': ['error', { patterns: [{ group: deny.flatMap(alias), message }] }]
		}
	}
}

const MODULES_DIR = fileURLToPath(new URL('./src/modules', import.meta.url))

function readModuleNames() {
	try {
		return readdirSync(MODULES_DIR, { withFileTypes: true })
			.filter(entry => entry.isDirectory())
			.map(entry => entry.name)
	} catch {
		return []
	}
}

/**
 * A module may import a sibling's public index (`@modules/library`) but never
 * reach inside it (`@modules/library/model/...`). Its own deep paths stay
 * legal, so the deny list is generated per module with a negated self-pattern.
 *
 * This is the rule that makes the public API mean something: without it, the
 * index file is documentation rather than a boundary.
 */
function crossModuleDeepImportRules() {
	return readModuleNames().map(name => ({
		files: [`src/modules/${name}/**/*.{ts,tsx}`],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							group: [
								'@modules/*/*',
								'@modules/*/*/**',
								`!@modules/${name}/*`,
								`!@modules/${name}/*/**`
							],
							message:
								'Import a sibling module through its public index (`@modules/<name>`), not a deep path.'
						},
						{
							group: alias('app'),
							message:
								'A module must not import app. Composition depends on modules, never the reverse.'
						}
					]
				}
			]
		}
	}))
}

export default tseslint.config(
	{
		ignores: [
			'out/**',
			'dist/**',
			'release/**',
			'node_modules/**',
			// Generated by `npm run api:types`.
			'src/core/*/*.gen.ts',
			// Declaration files carry no logic to lint.
			'**/*.d.ts'
		]
	},

	js.configs.recommended,
	...tseslint.configs.recommended,

	// Build and tooling scripts: linted, but not type-aware. They are not part
	// of either TypeScript project, and pretending otherwise only produces
	// "file not found in project" noise.
	{
		files: ['**/*.mjs'],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: globals.node
		}
	},

	// ── Renderer ────────────────────────────────────────────────────────────
	{
		files: ['src/**/*.{ts,tsx}', 'vitest.setup.ts'],
		languageOptions: {
			parserOptions: {
				project: './tsconfig.web.json',
				ecmaFeatures: { jsx: true }
			},
			globals: globals.browser
		},
		plugins: {
			react: reactPlugin,
			'react-hooks': reactHooks
		},
		settings: { react: { version: 'detect' } },
		rules: {
			...reactPlugin.configs.flat.recommended.rules,
			...reactHooks.configs.recommended.rules,
			// The JSX transform makes the React import unnecessary.
			'react/react-in-jsx-scope': 'off',
			'react/prop-types': 'off',
			'@typescript-eslint/consistent-type-imports': [
				'error',
				{ prefer: 'type-imports', fixStyle: 'separate-type-imports' }
			],
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
			]
		}
	},

	// ── Main process and preload ────────────────────────────────────────────
	{
		files: ['electron/**/*.ts', 'electron.vite.config.ts', 'vitest.config.ts'],
		languageOptions: {
			parserOptions: { project: './tsconfig.node.json' },
			globals: globals.node
		},
		rules: {
			// The main process must not reach into the renderer at all. They run in
			// different processes — an import that looked like it worked would
			// bundle renderer code into the main process.
			'no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							group: ['@app/*', '@modules/*', '@core/*', '@ui/*', '@lib/*'],
							message: 'The main process must not import renderer code — they are separate processes.'
						}
					]
				}
			]
		}
	},

	// ── Dependency directions ───────────────────────────────────────────────
	layer(
		['src/lib/**/*.{ts,tsx}'],
		['ui', 'core', 'modules', 'app'],
		'`lib` holds generic technical primitives and may import nothing above it. ' +
			'A utility that knows about media, playback or the node belongs to a module.'
	),
	layer(
		['src/ui/**/*.{ts,tsx}'],
		['core', 'modules', 'app'],
		'`ui` is the design system: domain-free and infrastructure-free. ' +
			'A component that knows what a title or a download is belongs to its module.'
	),
	layer(
		['src/core/**/*.{ts,tsx}'],
		['modules', 'app'],
		'`core` is application infrastructure and must not know about any domain. ' +
			'Core means "everyone needs it and it has no owner", not "it is important".'
	),

	...crossModuleDeepImportRules(),

	prettierConfig
)